### ISSUE TITLE
Type-incorrect expr passes shouldNotTypecheck

### ISSUE THREAD

**Issue by mitchellwrosen** [CRogers/should-not-typecheck#8]
I found an odd case that passes `shouldNotTypecheck`:

``` haskell
class Foo f where
  foo :: f a -> f a -> ()

instance Foo Maybe where
  foo _ _ = ()

main :: IO ()
main = shouldNotTypecheck (foo (Just True) (Just 'x'))
```

Output:

```
foo.hs:12:50: Warning:
    Couldn't match expected type ‘Bool’ with actual type ‘Char’
    In the first argument of ‘Just’, namely ‘'a'’
    In the second argument of ‘foo’, namely ‘(Just 'a')’
    In the first argument of ‘shouldNotTypecheck’, namely
      ‘(foo (Just True) (Just 'a'))’
foo.hs: HUnitFailure (Just (Location {locationFile = "src/Test/ShouldNotTypecheck.hs", locationLine = 26, locationColumn = 16})) "Expected expression to not compile but it did compile"
```

**Comment by mitchellwrosen** [comment]
Ah, I must be misunderstanding how the library works. I kicked the tires a bit and got it to work as expected:

``` haskell
class Foo f where
  foo :: NFData a => f a -> f a -> ()

instance Foo Maybe where
  foo x y = x `deepseq` y `deepseq` ()

main :: IO ()
main = shouldNotTypecheck (foo (Just True) (Just 'x'))
```

**Comment by CRogers** [comment]
Yes, unfortunately you have to deeply force the values so that the deferred type errors get evaluated and bubble up to the top. It would be great if there some kind of way to do this in haskell once in the library without having to litter `deepseq` everywhere. Maybe the StrictHaskell extension (or whatever it is in GHC 8.0 can help). I tend to use this library for testing type level stuff where everything is a `Proxy`, so no evaluation problems. If you have any ideas to make your situation better feel free to share (or even submit code) :)
